import type { Metadata } from 'next';
import Image from 'next/image';
import { PageShell } from '@/components/site-chrome';

export const metadata: Metadata = { title: 'Platform — AMHSTrafficLab', description: 'Traffic dynamics, system architecture, and simulation objects in AMHSTrafficLab.' };

export default function PlatformPage(){return <PageShell>
  <section className="page-hero platform-hero"><div><div className="section-label lime">PLATFORM OVERVIEW</div><h1>How AMHSTrafficLab represents and executes traffic.</h1><p>The platform provides vehicle motion, shared-resource access, task processing, controlled regions, and experiment execution. Researchers supply the routing or regional-control method.</p></div><figure className="platform-hero-figure"><Image src="/paper/gui.webp" width={842} height={462} priority alt="AMHSTrafficLab graphical interface showing the network, run controls, system health, and detailed metrics"/></figure></section>
  <section className="light-section architecture-section"><div className="section-label">SYSTEM ARCHITECTURE</div><div className="section-heading"><h2>Scenario configuration and recorded metrics</h2><div className="descriptive-copy"><p>A scenario fixes the network, fleet, demand, and controlled regions. During a run, the simulator advances vehicle motion, task progress, and shared-resource occupancy while the selected methods observe state and return decisions.</p><p>The evaluator uses the same run-level metric definitions for every method.</p></div></div><figure className="paper-figure"><Image src="/paper/architecture.webp" width={1555} height={759} alt="AMHSTrafficLab architecture linking scenarios, controllers, simulation, and evaluation"/></figure></section>
  <section className="light-section representation-section"><div className="section-label">SIMULATION OBJECTS</div><div className="section-heading"><h2>Simulation objects</h2><div className="descriptive-copy"><p>The rail network is directed. Control nodes represent splits and merges, while merge resources coordinate right-of-way where several approaches share a downstream track.</p><p>Each OHT executes a transportation task from pickup to delivery. WaterLevelArea objects group parts of the network for occupancy-based admission.</p></div></div><figure className="paper-figure"><Image src="/paper/simulation-objects.webp" width={1607} height={627} alt="Core AMHSTrafficLab objects: rail paths, control nodes, merge resources, OHTs, tasks, routes, and controlled areas"/></figure></section>
</PageShell>}
