import type { Metadata } from 'next';
import Image from 'next/image';
import { PageShell } from '@/components/site-chrome';

export const metadata: Metadata = { title: 'Validation — AMHSTrafficLab', description: 'How AMHSTrafficLab is validated as a fair, repeatable benchmark for routing and regional traffic control.' };

export default function ValidationPage(){return <PageShell>
  <section className="paper-hero"><div className="paper-badge">BENCHMARK VALIDATION</div><h1>Validation protocol and selected results.</h1><p>The experiments check whether traffic conditions remain consistent, whether regional control sustains operation, and whether method differences can be observed across maps and loads.</p><a className="button primary" href="#control-result">View regional-control results</a></section>

  <section className="light-section evaluation-protocol"><div className="section-label">VALIDATION PROTOCOL</div><div className="section-heading"><h2>Repeated runs under matched conditions</h2><p>The protocol separates differences caused by the method from differences caused by the traffic environment.</p></div><div className="protocol-strip"><article><strong>13</strong><span>routing methods</span></article><article><strong>7</strong><span>operating scenarios</span></article><article><strong>10</strong><span>shared seeds per scenario</span></article><article><strong>20,000 s</strong><span>per simulated run</span></article></div><div className="metric-ribbon"><span>Throughput</span><span>Cycle time</span><span>Travel-time index</span><span>OHT utilization</span><span>Throughput collapse</span><span>Circular waits</span></div></section>

  <section className="dark-section evidence-section" id="control-result"><div className="section-label lime">REGIONAL-CONTROL EFFECT</div><div className="section-heading"><h2>Regional-control results</h2><div className="descriptive-copy"><p>Across the tested routing methods and operating scenarios, regional admission substantially reduces runs with throughput collapse or confirmed circular waits. Without regional control, most confirmed circular waits remain inside a single Bay; some extend across a larger part of the network.</p><p>The detector reconstructs waiting dependencies and reports the number and spatial extent of vehicles involved in a confirmed cycle.</p></div></div><div className="loss-grid"><article><span>THROUGHPUT COLLAPSE RUNS</span><div><strong>265</strong><i>→</i><strong>9</strong><i>→</i><strong>3</strong></div><p>No regional control · admission · admission + rebalancing</p></article><article><span>CONFIRMED CIRCULAR-WAIT RUNS</span><div><strong>295</strong><i>→</i><strong>6</strong><i>→</i><strong>7</strong></div><p>No regional control · admission · admission + rebalancing</p></article></div><p className="result-note">Aggregated over 910 method–scenario–seed runs per control condition. Circular-wait detection and throughput collapse are separate run-level indicators.</p><figure className="paper-figure dark-figure"><Image src="/paper/deadlock-scale.webp" width={1300} height={462} alt="Distribution of confirmed circular waits by vehicles involved and spatial extent"/></figure></section>

  <section className="light-section rebalancing-section"><div className="section-label">EMPTY-VEHICLE REBALANCING</div><div className="section-heading"><h2>Results by operating point</h2><div className="descriptive-copy"><p>Under Dijkstra routing, mean cycle time decreases in the two Large scenarios and increases in SMALL 150.</p><p>Throughput remains stable, utilization falls, and the travel-time index can rise slightly. The result suggests that the main effect is vehicle availability rather than shorter travel paths in every scenario.</p></div></div><div className="finding-cards"><article><span>LARGE 275</span><strong>−14.4 s</strong><p>mean cycle time with rebalancing</p></article><article><span>LARGE 300</span><strong>−18.9 s</strong><p>mean cycle time with rebalancing</p></article><article className="caution"><span>SMALL 150</span><strong>+12.3 s</strong><p>mean cycle time with rebalancing</p></article></div><figure className="paper-figure"><Image src="/paper/rebalancing-effects.webp" width={1441} height={446} alt="Cycle time, travel-time index, utilization, and throughput with and without empty-vehicle rebalancing"/></figure></section>

  <section className="routing-result"><div><div className="section-label lime">ROUTING COMPARISON</div><h2>Results by operating scenario</h2><p>Classical, adaptive, Q-routing, neural, and multi-agent methods run through the same interface and traffic system.</p></div><div className="routing-evidence"><strong>13 × 7</strong><p>routing methods across operating scenarios</p><span>At lower loads, cycle time separates methods. At the largest loads, stability and served throughput also become important.</span></div></section>

  <section className="evaluation-note light-section"><div className="section-label">SCOPE OF THIS WEBSITE</div><h2>Selected figures and results</h2><p>The manuscript remains the authoritative source. A public manuscript link will be added when the paper is ready for release.</p></section>
</PageShell>}
