'use client';

import { useState } from 'react';
import Image from 'next/image';

export function MapExplorer(){
  const environments={small:{label:'Small',src:'/references/small-map.png',width:1884,height:476,title:'Small benchmark environment',shape:'3,334 nodes · 3,419 tracks · 56 regions',focus:'100 / 150 OHTs · 2,400 / 3,120 tasks per hour'},medium:{label:'Medium',src:'/references/medium-map.png',width:1908,height:910,title:'Medium benchmark environment',shape:'2,782 nodes · 3,174 tracks · 186 regions',focus:'175 / 200 / 225 OHTs · 4,850–6,100 tasks per hour'},large:{label:'Large',src:'/references/large-map.png',width:1886,height:772,title:'Large benchmark environment',shape:'3,522 nodes · 4,014 tracks · 224 regions',focus:'275 / 300 OHTs · 6,850 / 7,350 tasks per hour'}} as const;
  const [selected,setSelected]=useState<keyof typeof environments>('medium'); const item=environments[selected];
  return <div className="interactive-shell map-explorer" id="map-explorer"><div className="module-tabs" role="tablist" aria-label="Benchmark environment scale">{Object.entries(environments).map(([key,value])=><button type="button" key={key} onClick={()=>setSelected(key as keyof typeof environments)} className={selected===key?'is-active':''} aria-pressed={selected===key}><b>{value.label}</b><span>environment</span></button>)}</div><div className="map-stage"><div className="evidence-image benchmark-map-image"><Image src={item.src} alt={`${item.title} rendered by AMHSTrafficLab`} width={item.width} height={item.height} priority/></div><div className="map-stage-info"><span className="live-chip"><i/> Authorized platform render</span><h3>{item.title}</h3><dl><div><dt>Scale class</dt><dd>{item.label}</dd></div><div><dt>Network</dt><dd>{item.shape}</dd></div><div><dt>Tested operating points</dt><dd>{item.focus}</dd></div></dl><p>The same policy interface is used across maps; each map keeps its embedded task-generation defaults.</p></div></div></div>;
}

export function TrafficDynamicsViewer(){
  return <div className="interactive-shell dynamics-viewer" id="traffic-dynamics"><div className="evidence-ribbon"><span><i/> Recorded simulation playback</span><span>OHT TRAFFIC · CONTINUOUS LOOP</span></div><div className="dynamics-stage"><div className="evidence-image traffic-video"><video autoPlay muted loop playsInline controls preload="metadata" poster="/references/oht-traffic-poster.jpg" aria-label="AMHSTrafficLab OHT traffic simulation running over the rail network"><source src="/references/oht-traffic-loop.mp4" type="video/mp4"/>Your browser does not support embedded video.</video></div><div className="dynamics-copy"><span>RECORDED RUN</span><h3>Vehicle states during simulation.</h3><p>OHTs move, wait, pick up, and deliver while the platform updates rail occupancy and local access decisions.</p><div className="state-legend"><small className="idle">Idle</small><small className="pickup">Moving to pickup</small><small className="loading">Loading</small><small className="delivery">Moving to delivery</small><small className="unloading">Unloading</small><small className="wait">Long wait</small></div><a className="full-demo-link" href="/references/AMHSTrafficLab_Introduction.mp4" target="_blank" rel="noreferrer">Watch the full 2-minute platform demonstration ↗</a><p className="evidence-note">Authorized AMHSTrafficLab screen recording. The values shown are an example run, not a method comparison.</p></div></div></div>;
}
